---
- hosts: 192.168.1.47
  remote_user: root
  #Continuan las tareas
  tasks:
  #Empaquetando archivos descargados
  - name: Empaquetando archivos
    shell: tar -cf /root/archivos.tar /prueba
    #archive:
     # path: /prueba
     # dest: /root/archivos.tar

- hosts: 192.168.1.117
  remote_user: root
  tasks:
  - name: Copiando desde SDA a cliente (from serverA to serverB)
    synchronize:
      src: /root/archivos.tar
      dest: /tmp
    delegate_to: 192.168.1.47
  #DESempaquetando archivos descargados
  - name: Desempaquetando archivos descargados
    unarchive:
      src: /tmp/archivos.tar
      dest: /prueba
      remote_src: yes
- name: Llamar P3
  include: P3_execute_script.yml
...
