---
- hosts: 192.168.1.47
  remote_user: root
  #Continuan las tareas
  tasks:
  #ejecutando script en SDA
  - name: Dando permisos de ejecucion a script en SDA
    shell: chmod +x /prueba/pruebados/script.sh
  - name: Ejecutando script en SDA
    shell: /prueba/pruebados/script.sh

- hosts: 192.168.1.117
  remote_user: root
  tasks:
  - name: Dando permisos de ejecucion a script en SDA
    shell: chmod +x /prueba/prueba/pruebados/script.sh
  - name: Ejecutando script en Cliente
    shell: /prueba/prueba/pruebados/script.sh
...
