---
- hosts: sda
  remote_user: root
  #Continuan las tareas
  
  tasks:
  #Empaquetando archivos descargados
  - name: Empaquetando archivos  
    #shell: tar -cf /root/archivos.tar /prueba 
    archive:
      path: /prueba
      dest: /root/archivos.gz
      format: gz

- hosts: sucursales
  remote_user: root
  tasks:
  - name: verificando sha
    stat:
      path: /root/archivos.gz
      checksum_algorithm: sha1
    delegate_to: 192.168.1.47
    register: num1
  - name: verificando sha2
    stat:
      path: /tmp/archivos.gz
      checksum_algorithm: sha1
    register: num2

#  - name: Validacon Do-Until Loops
#    shell: scp root@192.168.1.47:/root/archivos.gz /tmp 
#    register: prueba

  - name: depurando
    debug:
     msg: "el archivo es el mismo"
    when: num1.stat.checksum != num2.stat.checksum
...
