---
- name: Registrar VM
  hosts: 192.168.1.115
  remote_user: root

 #Asignar variables
  vars:
  - rhn_user: gvalentin@ipcom.com.mx
  - rhn_password: tavo0610
  - rhn_vm_hosts: 192.168.1.115
  - hostname: bd.ipcom.com.mx

  #Inician las tareas
  tasks:
  - name: Registrar VM a rhn
    redhat_subscription:
     username: "{{ rhn_user }}"
     password: "{{ rhn_password }}"
     consumer_name: "{{ hostname }}"
     force_register: yes
     state: present
     autosubscribe: yes

  #Habilitar repositorioa
  - name: Habilitar repositorios
    command: "subscription-manager attach --auto"

  #Instalar BD
  - name: Instalar Maria DB Server
    yum:
     name: 'mariadb-server'
     state: present

  - name: Instalar Maria DB
    yum:
     name: 'mariadb'
     state: present

  #Iniciar y habilitar servicio
  - name: Iniciar servicio Maria DB
    service:
     name: mariadb
     state: started
     enabled: yes
...